// story.js

const phonePages = [
  "It all started when I was just laying on my bed. I was so bored. My friends were all busy, some doing school activities, others just playing.",
  "I thought I could talk to a new person. I always thought making new friends was a good idea.",
  "I asked my friend Ahron if he had someone I could talk to. I also told him I wanted to talk to a girl haha.",
  "He told me about this girl named Ciara. I searched for her socials and found her. I started talking to her — wow.",
  "She was kind, sweet, and friendly. We started talking and getting to know each other. Asking about hobbies, interests...",
  "While we talked, I started to feel comfortable around her. She's just so fun to talk to.",
  "After a few more weeks, we knew each other so well — birthdays, favorite foods, favorite colors.",
  "We kept talking like there was no tomorrow.",
  "After a few more months, I realized I had feelings for her. I confessed.",
  "She told me she liked me too, so I courted her.",
  "My friends thought me and Ciara should meet up. I thought it was a bad idea at first.",
  "We had only talked for a few months, and now we were meeting up? I was scared.",
  "I was scared because I knew I was ugly. I told her I didn't want to meet up. I was scared of judgment.",
  "She said, 'Don't worry, I don't care about looks. All I want is your personality.' She reassured me.",
  "The night before we met, I was excited and scared at the same time.",
  "After school, my friends and I went to the meetup place. Traffic was bad.",
  "Ciara and Ahron were waiting at a convenience store. I arrived late.",
  "Then I saw her — Ciara sitting on a bench. I just stood there, staring at her perfect face.",
  "No one made a move. Ahron pushed me in front of Ciara. I fell on the same bench she was on.",
  "As I stood up to sit properly, Ciara hugged me. I hugged her back. My first hug from a girl ever.",
  "We talked for a bit — how we were, how school was.",
  "Then, out of nowhere, she gave me her hairtie. She said, 'Take care of it. When you miss me, hold it.'",
  "I hugged her again. I was so glad.",
  "We went inside the convenience store. I was too shy to talk to her, so I talked to Ahron instead.",
  "Ahron asked, 'Why aren't you talking to her, bro?' I laughed it off. Ciara was behind me.",
  "Then, Ciara hugged me from behind. I felt butterflies. I was really blushing.",
  "We bought snacks and went outside to find a place to hang out.",
  "While crossing the road, Ciara held my hand. I fell even harder for her.",
  "It was my first time holding a girl's hand. Her hands were soft. I didn’t want to let go.",
  "We ate our snacks and talked for hours until sunset. We watched it together, holding hands.",
  "It was the best day of my life. But then, she had to go home before dark.",
  "I led her to the bus station. We hugged. She got on the bus. I waved goodbye.",
  "While I rode my bus home, I kept smiling, thinking about that day.",
  "I texted her when I got home. She replied quickly, saying she got home safe. We talked, then went to sleep.",
  "I had such a good sleep that night. I even dreamed about the day. I woke up happy.",
  "I wanted to meet her again, but she had strict parents. She said maybe in a few weeks.",
  "It didn't matter much. I was just glad we could still talk through text.",
  "Months passed, and our relationship stayed strong. Even with problems, we found ways to fix them.",
  "Then, one day, she told me something. Her old crush texted her, asking to meet.",
  "She told me about him — a classmate from grade 3. They liked each other, but she changed schools.",
  "I said it was okay if she wanted to meet him. I felt jealous but didn’t show it. I played games to forget.",
  "After that, she started getting distant. Cold. I felt the spark was fading.",
  "Weeks later, she told me she got back with that guy. I was devastated. I cried all night.",
  "I kept thinking — what did I do wrong? What did I do to deserve this?",
  "A few days later, Ciara blocked me on all socials. I wanted to end everything.",
  "Then... she unblocked me. I said, 'I still love you,' not expecting a reply. But she did.",
  "We talked for a bit. I asked if I could meet her one last time. I didn’t expect her to agree. But she did.",
  "On the meetup day, I saw her from afar. I walked toward her, wanting to hug her but too shy.",
  "Ahron was there. He asked if I had something to say, but I was speechless.",
  "When he left, Ciara said she couldn't stay long. As she was about to leave, I hugged her tight.",
  "I didn’t want to let go. She hugged me too, saying, 'It's okay.'",
  "People around us were saying we looked cute, but I was just about to cry.",
  "When she left, I sobbed. I regretted not saying anything while I had the chance.",
  "And after that day, we never talked again.",
  "Maybe she was the right person at the wrong time. Or maybe... we weren’t meant to be at all.",
  "First love has to be the worst."
];

const tabletPages = [];
for (let i = 0; i < phonePages.length; i += 2) {
  tabletPages.push([phonePages[i], phonePages[i + 1] || ""]);
}

export { phonePages, tabletPages };
